#!/bin/bash

# Exit script on first failure
set -e

# Echo commands to stdout.
set -x

# $IMAGE_NAME var is injected into the build so the tag is correct.

docker build \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --tag "$IMAGE_NAME" \
  .
